workflows:
  android-build:
    name: Build Android APK with Java 21
    max_build_duration: 60
    environment:
      # Optionnel: tu peux définir ici un JAVA_HOME par défaut
      JAVA_HOME: /usr/local/opt/openjdk@21
    scripts:
      - name: Installer openjdk 21
        script: |
          brew install openjdk@21
          echo "export JAVA_HOME=$(/usr/libexec/java_home -v 21)" >> $BASH_ENV
          echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV
      - name: Vérifier Java
        script: |
          source $BASH_ENV
          java -version
          javac -version
      - name: Build APK
        script: |
          source $BASH_ENV
          cd android
          ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
