workflows:
  build-android-capacitor:
    name: Build Android APK (Capacitor)
    max_build_duration: 20
    environment:
      vars:
        java_version: 17.0.0
        android_sdk: 30.0.3
        android_ndk: 21.4.7075529
        node_version: 20.10.0
      node: 20.10.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Copy web assets
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
