workflows:
  build-android-capacitor:
    name: Build Android APK (Capacitor)
    max_build_duration: 20
    environment:
      vars:
        JAVA_HOME: /path/to/jdk17
      android:
        java_version: 17
      node: 20.10.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Copy web assets
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
