workflows:
  android-capacitor:
    name: Build Android App with Capacitor
    environment:
      vars:
        JAVA_HOME: /opt/buildagent/java/openjdk-17
      android_signing:
        - keystore_reference
      node: 20.10.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build || echo "No build script, skipping..."
      - name: Copy web assets to native platforms
        script: |
          npx cap sync
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
