workflows:
  capacitor-android:
    name: Build Android APK for Capacitor
    environment:
      node: 20.11.1 # ✅ Version compatible avec Capacitor 5
    scripts:
      - npm ci
      - npx cap sync android
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
