workflows:
  build-android:
    name: Build Android APK (Capacitor)
    max_build_duration: 20
    environment:
      vars:
        JAVA_HOME: /usr/libexec/java_home -v 17
      android:
        java_version: 17
    scripts:
      - echo "Using Java version:"
      - java -version
      - ./gradlew clean
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
