workflows:
  android-build:
    name: Build Android APK
    environment:
      node: 20.10.0
      java: 17
    scripts:
      - name: Installer les dépendances
        script: |
          npm install
      - name: Copier les fichiers web
        script: |
          npx cap sync
      - name: Construire l'APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
