workflows:
  android-build:
    name: Android Build
    environment:
      sdk: 34
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web assets
        script: npm run build || echo "skip if not using build"
      - name: Sync Capacitor
        script: npx cap sync
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
