workflows:
  android-capacitor:
    name: Build Android App with Capacitor
    environment:
      java: 17
      JAVA_HOME: /opt/buildagent/java/openjdk-17
      android_signing:
        - my_keystore
      node: 18.16.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build || echo "No build script, skipping..."
      - name: Sync Capacitor
        script: |
          npx cap sync
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
