workflows:
  build-android:
    name: Build Android APK (Capacitor)
    max_build_duration: 20
    scripts:
      - echo "Liste des versions Java dispo"
      - /usr/libexec/java_home -V
      - echo "Set JAVA_HOME to Java 17"
      - export JAVA_HOME=$(/usr/libexec/java_home -v 17)
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - cd android && ./gradlew clean assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
